apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
        tier: app
    spec:
      containers:
      - name: postgres
        image: postgres:9
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: mattermost-secret
              key: mm-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mattermost-secret
              key: mm-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: mattermost-config
              key: db-name
